name: CI

on:
  pull_request:
    branches: [main]   # PRs targeting main; drop this line to run on all PRs

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/filipjsowa/fprime-arm:4.1.1

    steps:
      - uses: actions/checkout@v7
        with:
            submodules: recursive

      - run: |
          fprime-util generate aarch64-linux
          fprime-util build aarch64-linux